apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openingtrade.fullname" . }}
  labels:
    {{- include "openingtrade.labels" . | nindent 4 }}
data:
  symbols: |
    {{- toYaml .Values.alpaca.symbols | nindent 4 }}
