apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "openingtrade.fullname" . }}
  labels:
    {{- include "openingtrade.labels" . | nindent 4 }}
data:
  APCA_API_KEY_ID: {{ required "Please set alpaca.key" .Values.alpaca.key | b64enc }}
  APCA_API_SECRET_KEY: {{ required "Please set alpaca.secret" .Values.alpaca.secret | b64enc }}
